### PR TITLE
My own modifications that might be worth something

### PR DESCRIPTION
**Pull request by Almamu**
MISC: Prevent other people from uploading their upgrade stuff
ADD: Texture chunks have a palette on it (first 16 lines of texture data), add support to load them and display the current texture in any of those although I'm not sure at all if paletes are shared between texture chunks too
ADD: Support for displaying whole level geometry in a popup window (doesnt include zone data). Should work with all crash releases (only tested Crash 1, 2, 3, don't have prototypes to test it)
FIX: Do not open full scenery view when there aren't any scenery entries
ADD: Load all the zone data in the NSF file and display in a popup in the scenery fashion. WARNING: This is slow but there should be a way to optimize this.

Signed-off-by: Almamu almamu@almamu.com

### CODE REVIEW

**Comment by ManDude** [comment]
The first 16 lines of data are not always palettes. I am thinking of adding some sort of texture viewer like PVV which lets you select the palette and the texture and it will map the colors correctly. I'll try this out and see how it works.

**Comment by Almamu** [comment]
Yes, not every texture has those first blocks as a palette (for example, universal logo in crash2 is rgb555 format). The thing is that the texture itself doesn't have any information about that afaik, that information is in the models that use the texture (one flag for color mode and texture index in the texture chunk if i'm not mistaken). Anyway It's just a dirty and fast fix to correctly see the textures used in the game for now, but It definetly needs improvement.

I'm working on exporters to obj and trying to add support for texture stuff in the model viewer as It's completely missing right now.

**Review by AraHaan — CHANGES_REQUESTED** [review]
Currently with your Changes there is a problem when compiling:

```
Controllers\NSFController.cs(432,55): error CS7036: There is no argument given
that corresponds to the required formal parameter 'linkedentries' of 'ProtoZoneEntryViewer.ProtoZoneEntryViewer(ProtoZoneEntry, ProtoSceneryEntry[], ProtoZoneEntry[])'
[E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
Controllers\NSFController.cs(471,53): error CS7036: There is no argument given
that corresponds to the required formal parameter 'linkedentries' of 'OldZoneEntryViewer.OldZoneEntryViewer(OldZoneEntry, OldSceneryEntry[], OldZoneEntry[])'
[E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
Controllers\NSFController.cs(511,50): error CS7036: There is no argument given
that corresponds to the required formal parameter 'linkedentries' of 'ZoneEntryViewer.ZoneEntryViewer(ZoneEntry, SceneryEntry[], ZoneEntry[])' [E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
Controllers\NSFController.cs(551,53): error CS7036: There is no argument given
that corresponds to the required formal parameter 'linkedentries' of 'NewZoneEntryViewer.NewZoneEntryViewer(NewZoneEntry, NewSceneryEntry[], NewZoneEntry[])' [E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
```

You need to add in a 3rd parameter of ``entries.ToArray()`` on lines ``432``, ``471``. ``511``, and ``551`` Will result in:

```
Controllers\NSFController.cs(432,76): error CS1503: Argument 1: cannot convert
from 'System.Collections.Generic.List<Crash.ProtoZoneEntry>' to 'Crash.ProtoZoneEntry' [E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
Controllers\NSFController.cs(471,72): error CS1503: Argument 1: cannot convert
from 'System.Collections.Generic.List<Crash.OldZoneEntry>' to 'Crash.OldZoneEntry' [E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
Controllers\NSFController.cs(511,66): error CS1503: Argument 1: cannot convert
from 'System.Collections.Generic.List<Crash.ZoneEntry>' to 'Crash.ZoneEntry' [E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
Controllers\NSFController.cs(551,72): error CS1503: Argument 1: cannot convert
from 'System.Collections.Generic.List<Crash.NewZoneEntry>' to 'Crash.NewZoneEntry' [E:\Users\Elsword\Desktop\CrashEdit-newgui\CrashEdit\CrashEdit.csproj]
```

Maybe somehow go in that list and somehow combine the information from each entry to where it looks as if it is 1 entry to fix this?

**Comment by Almamu** [comment]
Im reviewing this because my local copy compiles just fine, give me a couple of hours.

**Comment by Almamu** [comment]
Ok, these changes should fix the problem and add the missing stuff that somehow I didn't upload to the repo. Sorry for the inconvenience. It also adds the obj exporter code that was missing from those commits too. Now it's possible to export the whole level geometry (without colors) to OBJ. REMEMBER! The models DO NOT have textures in them.

EDIT: @AraHaan you might be interested in this project too: https://github.com/Almamu/crashutils
I've updated it to compile with vs 2015, it still has some memory leaks that i want to fix, but you can even play a level from crash1 without much stuff missing :D

**Comment by AraHaan** [comment]
Please work on exporting the textures from the sceneries to tga's without having to worry about generating 8 MB tga files per part of the sceneries as that would be good as well as a way to convert back to original format for when someone edits them.

**Comment by ManDude** [comment]
Much easier said than done, lol.

**Comment by AraHaan** [comment]
ok so @Almamu on https://github.com/Almamu/crashutils does it support playing an level from Crash 3 as well?

**Comment by Almamu** [comment]
@AraHaan it only supports crash 1 files

**Comment by AraHaan** [comment]
@Almamu In Crash Bandicoot 2 cortex Strikes back I have noticed the frequency of the Speech chunks is approximately 21025 on all of them. I am going to test this on Crash 3 now to see if it is the same for that game as well.

Edit: it is the same frquency on Crash Bandicoot 3 as well. It should work on all versions of Crash 2 & 3.

**Comment by ughman** [comment]
What makes you certain it's 21025? That's pretty close to 22050 which is a very common sample rate.

**Comment by ManDude** [comment]
Most SFX have a random sample rate when aged though it is around the 11khz range

**Comment by ManDude** [comment]
played* fuck mobile not allowing efits

**Comment by Almamu** [comment]
As far as I can remember the speech chunks were correctly played at 22050 and didn't sound bad (im not at my computer so I cant test it), but SFX do have some weird random sample rate, specially on crash 2 and 3. I don't know if there is any way of finding it from the game files or if that's fixed in the engine.

**Comment by AraHaan** [comment]
On the sounds some of them are 22050 as well.

**Comment by AraHaan** [comment]
@ManDude Was these changes superceeded or something?

**Comment by AraHaan** [comment]
Ah I see they was not applied at all; It seems because it is old it was closed. Maybe because it is not active and the fact that this fork seems unneeded anymore I personally need these changes so I am seeing if I can add these in manually.

**Comment by AraHaan** [comment]
@Almamu I updated the thing. Also export all sceneries as obj is broken when viewed in windows 10 view 3d thing.

image

**Comment by ManDude** [comment]
sorry, pulls here were automatically closed when i messed with the branches

**Comment by Almamu** [comment]
> 
> 
> @Almamu I updated the thing. Also export all sceneries as obj is broken when viewed in windows 10 view 3d thing.
> 
> image

I've just tested it with the warp room of Warped 3 and the export is done properly. I can load the whole warp room properly into paint 3d with the correct geometry: 
export paint3d


> 
> 
> sorry, pulls here were automatically closed when i messed with the branches

No problem, either way If there's a new tool I don't think this changeset is important at all anymore ;)

**Comment by AraHaan** [comment]
Well @Almamu the new tool does not support as much as crash edit. Also I updated the changeset on this to the current on Crash Edit. I also now have an open https://github.com/cbhacks/CrashEdit/pull/145, And merged a little change to fix the obj exporter on the ``NewSceneryEntry`` class that seems to have broken it for me. https://github.com/cbhacks/CrashEdit/pull/142

**Pull request closed without merging**
